/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VIEW;

import CONNECTION.DB_Connection;
import DAO.DAO_Key;
import DAO.DAO_Province;
import DAO.DAO_QR_Generator;
import DAO.DAO_RandomNumberGenerator;
import DAO.DAO_Validator;
import MODEL.MOD_Area;
import MODEL.MOD_Key;
import MODEL.MOD_Override_QR_Data;
import MODEL.MOD_Province;
import MODEL.MOD_Validator;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.json.JSONObject;

/**
 *
 * @author Long
 */
public class MobilePhoneValidator extends javax.swing.JInternalFrame {

    /**
     * Creates new form MobilePhoneValidator
     */
    private int[] occupiedValue = null;
    private int[] occupiedCoordinatesX = null;
    private int[] occupiedCoordinatesY = null;
    private String[] occupiedCoordinates = null;
    
    public MobilePhoneValidator() throws IOException {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;
        //setLocation(x, y-25);

        //this.setIconImage(Toolkit.getDefaultToolkit().getImage("image/icon.png"));
        //String PicURL = "image/logo.png";
        //ImageIcon picIcon = new ImageIcon(PicURL);
        //logo.setIcon(picIcon);

        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        
        // calling components
        initializeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelInformasiPerangkat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        InputComboProvince = new javax.swing.JComboBox();
        InputArea = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtTPSNo = new javax.swing.JTextField();
        txtDeviceIMEIPengawas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPengawasNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDeviceIMEIBilikSuara = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDeviceIMEITPS = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Validate Devices");
        setFrameIcon(new javax.swing.ImageIcon("C:\\Users\\Long\\Documents\\NetBeansProjects\\evotingGenerator\\image\\icon.png")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Input"));

        jButton1.setText("Add Device Informations (to Validate from Mobile Devices)");

        tabelInformasiPerangkat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelInformasiPerangkat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelInformasiPerangkatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelInformasiPerangkat);

        jLabel1.setText("Data TPS : (klik baris pada tabel untuk melengkapi informasi perangkat)");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cari Data"));

        jLabel5.setText("Provinsi :");

        InputComboProvince.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                InputComboProvinceItemStateChanged(evt);
            }
        });

        InputArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Pilih Provinsi>" }));
        InputArea.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                InputAreaItemStateChanged(evt);
            }
        });

        jLabel6.setText("Kab / Kota : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputComboProvince, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(InputComboProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(InputArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registrasi Informasi Perangkat"));

        txtTPSNo.setEditable(false);

        jLabel3.setText("Pengawas No. :");

        jLabel7.setText("Device IMEI Pengawas TPS :");

        jLabel8.setText("Informasi Perangkat Bilik Suara :");

        txtPengawasNo.setEditable(false);

        jLabel2.setText("TPS No. :");

        jLabel9.setText("MAC Address : ");

        jLabel4.setText("Device IMEI Panitia TPS :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTPSNo)
                    .addComponent(txtPengawasNo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDeviceIMEITPS)
                    .addComponent(txtDeviceIMEIPengawas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 206, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDeviceIMEIBilikSuara)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txtTPSNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeviceIMEITPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(txtPengawasNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeviceIMEIPengawas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtDeviceIMEIBilikSuara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputComboProvinceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_InputComboProvinceItemStateChanged
        // TODO add your handling code here:
        onProvinceComboChanged();
    }//GEN-LAST:event_InputComboProvinceItemStateChanged

    private void InputAreaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_InputAreaItemStateChanged
        // TODO add your handling code here:
        onAreaComboChanged();
    }//GEN-LAST:event_InputAreaItemStateChanged

    private void tabelInformasiPerangkatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelInformasiPerangkatMouseClicked
        // TODO add your handling code here:
        int ind = tabelInformasiPerangkat.getSelectedRow();
        displayRowData(ind);
    }//GEN-LAST:event_tabelInformasiPerangkatMouseClicked
    
    public void initializeComponents() throws IOException{
        DB_Connection dbc = new DB_Connection();
        List<MOD_Province> getAllProvince = (new DAO_Province(dbc.getConnection())).RetrieveProvinceData();

        for(MOD_Province GAP : getAllProvince) {
            InputComboProvince.addItem(GAP.getProvince_id()+" - "+GAP.getProvince());
        }
    }
    
    public void onProvinceComboChanged(){
        DB_Connection dbc;
        try {
            dbc = new DB_Connection();
        
            int province_id = Integer.parseInt(InputComboProvince.getSelectedItem().toString().substring(0,2));
            List<MOD_Area> getAllArea = (new DAO_Province(dbc.getConnection())).RetrieveAreaData(province_id);

            String debug = "";
            InputArea.removeAllItems();
            for(MOD_Area MA : getAllArea) {
                InputArea.addItem(MA.getArea_number()+" - "+MA.getArea_name());
            }
        } catch (IOException ex) {
            Logger.getLogger(MobilePhoneValidator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void onAreaComboChanged(){
        if(InputArea.getSelectedItem() != null){
            String provNumber = InputComboProvince.getSelectedItem().toString().substring(0,2);
            String areaNumber = InputArea.getSelectedItem().toString().substring(0,2);
            areaNumber = areaNumber.replaceAll("\\s+","");
            
            if(areaNumber.length() == 1){
                areaNumber = "0"+areaNumber;
            }
            String ProvArea = provNumber+areaNumber;
            DB_Connection dbc;
            try {
                dbc = new DB_Connection();
            
            List<MOD_Validator> getAllData = (new DAO_Validator(dbc.getConnection())).getAllValidator(ProvArea);
            String data[][] = new String[getAllData.size()][9];
            int i = 0;
            for(MOD_Validator MV : getAllData) {
                data[i][0] = String.valueOf(MV.getValidatorId());
                data[i][1] = MV.getProvinceName();
                data[i][2] = MV.getAreaName();
                data[i][3] = MV.getVoteLocation();
                data[i][4] = String.valueOf(MV.getNumberTPS());
                data[i][5] = String.valueOf(MV.getNumberPengawas());
                data[i][6] = String.valueOf(MV.getImeiPanitiaTPS());
                data[i][7] = String.valueOf(MV.getImeiPengawasTPS());
                data[i][8] = MV.getDeviceMACAddress();
                i++;
            }

            String title[] = {
                "No.", "Provinsi", "Kab/Kota", "Location Code", "TPS #", "Pengawas #", "Panitia TPS IMEI", "Pengawas TPS IMEI", "Perangkat MAC Address"
            };
            DefaultTableModel model = new DefaultTableModel(data, title);
            tabelInformasiPerangkat.setModel(model);
            DefaultTableCellRenderer align_center = new DefaultTableCellRenderer();
            align_center.setHorizontalAlignment(0);
            tabelInformasiPerangkat.getColumnModel().getColumn(0).setPreferredWidth(20);
            TableColumn col0 = tabelInformasiPerangkat.getColumnModel().getColumn(0);
            col0.setCellRenderer(align_center);
            tabelInformasiPerangkat.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabelInformasiPerangkat.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabelInformasiPerangkat.getColumnModel().getColumn(3).setPreferredWidth(30);
            TableColumn col3 = tabelInformasiPerangkat.getColumnModel().getColumn(3);
            col3.setCellRenderer(align_center);
            tabelInformasiPerangkat.getColumnModel().getColumn(4).setPreferredWidth(20);
            TableColumn col4 = tabelInformasiPerangkat.getColumnModel().getColumn(4);
            col4.setCellRenderer(align_center);
            tabelInformasiPerangkat.getColumnModel().getColumn(5).setPreferredWidth(20);
            TableColumn col5 = tabelInformasiPerangkat.getColumnModel().getColumn(5);
            col5.setCellRenderer(align_center);
            tabelInformasiPerangkat.getColumnModel().getColumn(6).setPreferredWidth(100);
            tabelInformasiPerangkat.getColumnModel().getColumn(7).setPreferredWidth(100);
            tabelInformasiPerangkat.getColumnModel().getColumn(8).setPreferredWidth(100);
            } catch (IOException ex) {
                Logger.getLogger(MobilePhoneValidator.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void displayRowData(int rowIndex) {
        int rows = rowIndex;
        Object rowData[] = new Object[tabelInformasiPerangkat.getColumnCount()];
        for (int col = 0; col < tabelInformasiPerangkat.getColumnCount(); col++) {
            rowData[col] = tabelInformasiPerangkat.getValueAt(rows, col);
        }

        String tpsNo = rowData[4].toString();
        String pengawasNo = rowData[5].toString();
        String imeiTps = rowData[6].toString();
        String imeiPengawas = rowData[7].toString();
        String macBilikSuara = rowData[8].toString();
        txtTPSNo.setText(tpsNo);
        txtPengawasNo.setText(pengawasNo);
        txtDeviceIMEITPS.setText(imeiTps);
        txtDeviceIMEIPengawas.setText(imeiPengawas);
        txtDeviceIMEIBilikSuara.setText(macBilikSuara);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox InputArea;
    private javax.swing.JComboBox InputComboProvince;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelInformasiPerangkat;
    private javax.swing.JTextField txtDeviceIMEIBilikSuara;
    private javax.swing.JTextField txtDeviceIMEIPengawas;
    private javax.swing.JTextField txtDeviceIMEITPS;
    private javax.swing.JTextField txtPengawasNo;
    private javax.swing.JTextField txtTPSNo;
    // End of variables declaration//GEN-END:variables
}
